dbt_airbnb:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.containers.internal
      user: postgres
      password: postgres
      port: 5432
      dbname: airbnb
      schema: dev
      threads: 1